### ISSUE TITLE
Add Entity.type

### ISSUE THREAD

**Issue by Adrodoc** [wizards-of-lua/wizards-of-lua#167] opened 2018-04-04 18:44 UTC
The issue with Entity.name is that:
1. It uses the custom name if present
2. It depends on the user language

Entity.type should use `net.minecraft.entity.EntityList.getKey(Entity)`

**Comment by mkarneim** [comment] 2018-08-27 15:38
This is a duplicate of #198

**Closed by mkarneim** 2018-08-27 15:38 UTC
Labels: duplicate
