### ISSUE TITLE
Wizards should be able to break specific spells

### ISSUE THREAD

**Issue by mkarneim** [wizards-of-lua/wizards-of-lua#45] opened 2017-08-28 11:03 UTC
This is an extension to the `/wol spell break all` command.

For example:
- `/wol spell break mickkay` breaks all spells belonging to player mickkay.
- `/wol spell break Spell-123` breaks the spell with SID 123.

**Comment by Adrodoc55** [comment] 2017-09-13 14:48
Even though you can kill spells in order to break them, it is probably a good idea to support breaking spells via selector:
`/wol spell break @e[tag=minecart]`
type=spell should be implied.

**Comment by Adrodoc55** [comment] 2017-09-13 15:03
Duplicate of #8

**Comment by mkarneim** [comment] 2017-09-21 18:04
For breaking spells by tag I have created issue #59

**Comment by mkarneim** [comment] 2017-09-21 18:09
I already fixed this issue locally.

Here is how it works:

```lua
/wol spell break byName Spell-1
```
will break all spells with name "Spell-1". Please note that a spell can change its name with ```lua spell.name="xxx"```.

```lua
/wol spell break bySid 15
```
will break the spell with the spell id 15.

```lua
/wol spell break byOwner mickkay
```
will break all spells owned by player mickkay.

**Closed** 2017-09-22 07:44 UTC
Labels: enhancement
