### ISSUE TITLE
Optional tags for spells

### ISSUE THREAD

**Issue by bytemage** [wizards-of-lua/wizards-of-lua#8] opened 2017-04-22 15:02 UTC
Selecting spells by tags, like it is possible for entities, would be a nice way to break a group of persistent spells. Currently breaking spells is either global or on a per spell basis.

**Comment by mkarneim** [comment] 2017-04-23 08:10
Yeah, the spell breaking admin command is only very basic right now.
Additional to your suggestion it would be nice to have an option to break only 'my' spells, or better, only spells casted by a specific user.

Regarding your suggestion:
Actually it is already possible to 'break' spells matching some selector criteria, although it is not supported directly by the admin command right now.
You can use the vanilla `/kill` command, e.g. `/kill @e[type=luamod.Spell,tag=myfunnytag]`. Of course that means that you have to 'tag' it before manually.

Anyway, I think this must be supported natively by Wol.

**Comment by Adrodoc55** [comment] 2017-04-25 16:15
Additionally we should implement a permission check so you can't break spells of other people unless you are op. This should include the /kill variant.

**Comment by mkarneim** [comment] 2017-04-25 16:59
Similar permission checks must also be performed when executing commands from Lua using `spell:execute( cmd)`. I have created an issue (#25) for this.

**Comment by Adrodoc55** [comment] 2018-01-19 19:02
@mkarneim this is either fixed via #45 or discarded via #59

**Comment by mkarneim** [comment] 2018-01-20 08:18
I close this, because this is a duplicate of #59.

Anyway, when #76 is fixed, you can implement a command like this by just delegating the call to 
```/kill @e[type=wol:spell,tag=mytag]```

**Closed by mkarneim** 2018-01-20 08:18 UTC
Labels: enhancement
